# ANT61 Internship - Work Shop 1 Tasks

#### Feedbacks from code sharing:
- Style, brackets around the operands in boolean operations
- Return functions/vlaues should also have type def

### Algorithms

1. Implement a stack with operations Push, Pop, Max, where each operation takes constant time to complete: O(c)

In [23]:
## Implement a node class for each node within the stack

class Node:
    def __init__(self, value: float, localMax: float):
        self.value = value
        self.localMax = localMax
        self.next = None

    def getLocalMax(self) -> float:
        return self.localMax

    def getValue(self) -> float:
        return self.value
    
    def getNext(self):
        return self.next
    
    def setNext(self, nextNode):
        self.next = nextNode


In [24]:
## Implement the stack class with the required operations.

class Stack:
    def __init__(self):
        self.head: Node = None
        self.size = 0

    def getSize(self):
        return self.size

    def Max(self):
        if self.head != None:
            return self.head.getLocalMax()
        return None
    
    def Pop(self):
        if self.size == 0:
            return None
        else:
            output = self.head
            self.head = self.head.getNext()
            return output
    
    def Push(self, value: float):
        if self.size == 0:
            newNode = Node(value, value)
        else:
            originalMax = self.head.getLocalMax()
            if value > originalMax:
                newNode = Node(value, value)
            else:
                newNode = Node(value, originalMax)
            newNode.setNext(self.head)
        self.head = newNode
        self.size += 1


In [25]:
# The following code is a general testing code for the first task
stack = Stack()
stack.Push(2)
stack.Push(1)
print(stack.Max())
stack.Push(6)
print(stack.Max())
stack.Pop()
print(stack.Max())
stack.Pop()
stack.Pop()
print(stack.Max())

2
6
2
None


2. You are given an input string as a sequence of brackets of different types  '(', ')', '[', ']', '{', ‘}’. We need to implement an algorithm that will check if the sequence is correct, i.e. there is a closing bracket for each opening bracket. For example
‘([{}])’ and ‘()()’ are correct, ‘[)’ and ‘[(])’ are not. The algorithm should be of O(n) complexity where n is the length of the input string.

Ideas: Go through each element of the expression, if the next symbol is a pair corresponding to the element, continue, stop and return false otherwise. Use a stack (LIFO) to store each of the opening brackets in the expression. Remove each successful pairs and return False if remaining opening brackets exist after iterating through the expression. (i.e., edge case of more opening brackets than the closing brackets.)

In [26]:
# Assumption: When the expression is None (i.e., no brackets exists), the expression should evaluted as True (i.e., balanced).

def checkBracketsBalanced(expression):
    bracketStack = []
    
    for bracket in expression:
        if bracket in ["(", "[", "{"]:
            bracketStack.append(bracket)
        
        else:
            if len(bracketStack) == 0:
                return False
            
            openingBracket = bracketStack.pop()
            if  openingBracket == "(":
                if bracket != ")":
                    return False
            elif openingBracket == "[":
                if bracket != "]":
                    return False
            elif openingBracket == "{":
                if bracket != "}":
                    return False
        
    if len(bracketStack) != 0:
        return False
    return True

In [27]:
## The following Code is couple simple tests to verify that checkBracketsBalanced() works accordingly

def testCheckBracketsBalanced():
    # This should return True
    expression_1 = "[{()}]"
    print(checkBracketsBalanced(expression_1))
    
    # This should return False
    expression_2 = "[)()]"
    print(checkBracketsBalanced(expression_2))

    # This should return True
    expression_3 = ""
    print(checkBracketsBalanced(expression_3))

    # This should return False
    expression_4 = "{[]()}{{})}"
    print(checkBracketsBalanced(expression_4))

    # This should return False
    expression_5 = "[(])"
    print(checkBracketsBalanced(expression_5))

testCheckBracketsBalanced()

True
False
True
False
False


### Matrices

In [99]:
# Import libraries required in the Matrices tasks
import numpy as np

In [100]:
# Create poorly named numpy arrays for usage in the following tasks
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 20, 3], [40, 5, 6], [7, 8, 9]])
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
e = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36]])
f = np.array([[6, 7], [10, 11]])
g = np.array([[13, 14, 15], [18, 19, 20], [23, 24, 25]])

# Print out these numpy arrays 
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)

[[1 2]
 [3 4]]

[[ 1 20  3]
 [40  5  6]
 [ 7  8  9]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


1. You are given a matrix of random numbers, you need to output the matrix where odd rows are swapped with even rows in the original matrix

In [102]:
def swapOddEvenRows(array):
    index = 0
    while index  < len(array) - 1:
        array[[index, index + 1]] = array[[index + 1, index]]
        index += 2

    return array

print(swapOddEvenRows(d))
print(swapOddEvenRows(d))

print(swapOddEvenRows(e))
print(swapOddEvenRows(e))



[[ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]
 [19 20 21 22 23 24]
 [13 14 15 16 17 18]
 [31 32 33 34 35 36]
 [25 26 27 28 29 30]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


2. You are given a matrix of random numbers, you need to find the number of the column which has the biggest number

In [103]:
def getColWithMax(array):
    return np.where(array == np.amax(array))[1]

# The value for this test should return "[1]" (The first column of an array is column 0)
print(getColWithMax(a))
# The value for this test should return "[0]" (The first column of an array is column 0)
print(getColWithMax(b))

[1]
[0]


3. You are given a matrix of random numbers, you need to find the number of the column which has the biggest sum of numbers

In [104]:
def getColWithMaxSum(array):
    columnSum = array.sum(axis=0)
    return np.where(columnSum == np.amax(columnSum))[0]

# The value for this test should return "[0]"
print(getColWithMaxSum(b))
# The value for this test should return "[5]"
print(getColWithMaxSum(e))

[0]
[5]


4. You are given a matrix of random numbers, you need to find the number of the column which has the biggest median of numbers

In [105]:
def getColWithMaxMedian(array):
    columnMedian = np.median(array, axis=0)
    return np.where(columnMedian == np.amax(columnMedian))[0]

# The value for this test should return "[1]"
print(getColWithMaxMedian(b))
# The value for this test should return "[5]"
print(getColWithMaxMedian(e))

[1]
[5]


5. You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions.

In [118]:
def findSmallMatrix2D(smallMatrix, bigMatrix) -> list[int]:
    pos_y_big: int = 0
    while (pos_y_big < len(bigMatrix)):
        pos_x_big: int = 0
        while (pos_x_big < len(bigMatrix[0])):
            if (bigMatrix[pos_y_big][pos_x_big] == smallMatrix[0][0]):
                equal_flag = 0
                pos_y_small = 0
                while (pos_y_small < len(smallMatrix)) and (equal_flag == 0):
                    pos_x_small = 0
                    while (pos_x_small < len(smallMatrix[0])) and (equal_flag == 0):
                        if (smallMatrix[pos_y_small][pos_x_small] != bigMatrix[pos_y_small+pos_y_big][pos_x_small+pos_x_big]):
                            equal_flag = 1
                        pos_x_small = pos_x_small + 1
                    pos_y_small = pos_y_small + 1
                if equal_flag == 0:
                    return [pos_x_big, pos_y_big]
            pos_x_big = pos_x_big + 1
        pos_y_big = pos_y_big + 1
    return None

In [121]:
def test_findSmallMatrix2D():
    # This test should return [1, 1]
    print(findSmallMatrix2D(f, c))
    # This test should return [2, 2]
    print(findSmallMatrix2D(g, d))
    # This test should return None
    print(findSmallMatrix2D(a, d))

test_findSmallMatrix2D()

[1, 1]
[2, 2]
None


6. You are given a big matrix, a smaller one and a number representing how much to rotate the smaller matrix in multipliers of  radians in increments of 0.5 (0, 0.5, 1, ...). Write a function that returns a copy of a big matrix where the smaller matrix is rotated  accordingly.

7. You are given the size of a matrix (e.g. width and height for 2D) and the coordinate of the start and the end of the line segment. Write a function that returns the matrix which has 1 where the line pixels should be and 0 where they shouldn’t. 
Draw the matrix as a graphical output. Start with 2d and experiment with higher dimensions.

8. Same as 3, but now with antialiasing, where the numbers in the resulting matrix represent the pixel transparency.

### Bonus Tasks

1. You are given a sequence $a_1,a_2,...,a_n \in N$, and $S \in N$. Implement a program that would find $l, r$:($1lrn)$ so that i=lrai=S: O(n)

In [90]:
def findSum(sequence: list[float], sum: float) -> list: 
    l = 0
    r = 0
    current_sum: float = 0

    while l < len(sequence):
        if current_sum == sum and l != 0 and r != l:
            return [r, l - 1]
        elif current_sum < sum:
            current_sum += sequence[l]
            l = l + 1
        else:
            current_sum = current_sum - sequence[r]
            r = r + 1
            
    return None

In [92]:
def test_findSum():
    list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    
    # The test should return in the following format [l, r]

    # This test should return [1, 2]
    print(findSum(list_1, 5))
    # This test should return None
    print(findSum(list_1, 0))
    # This test should return [2, 4]
    print(findSum(list_1, 12))

test_findSum()

[1, 2]
None
[2, 4]


2. You are given a sequence a1,a2,..., an Z. Implement a program that would find l, r:(1lrn) so that i=lraiwould be the maximum possible: O(n)

3. You are given a number nZ you need to implement a function that returns the square root of n: O(log n)